const srcObj = {
  last_notify: 10308673,
  list: [
    {
      barcode: 'cs59019',
      chassis: {
        id: null,
        name: null,
        server_slot_count: null,
        size: null,
        unit: null,
      },
      configuration: '',
      custom_configuration: null,
      diag_error: null,
      domain: 'cs59019.com',
      exploitation_status: 'in_exploitation',
      generated_configuration: '',
      has_errors: false,
      id: 3241,
      intel_amt: null,
      ip: [
        {
          domain: 'cs59019.com',
          family: 'ipv4',
          gateway: '94.198.51.254',
          id: 19367,
          name: '94.198.51.220',
          network: '94.198.51.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
        {
          domain: 'gamebrolive4.example.com',
          family: 'ipv4',
          gateway: '152.89.217.254',
          id: 19390,
          name: '152.89.217.119',
          network: '152.89.217.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
      ],
      ipmi: null,
      is_custom_configuration: false,
      is_new: false,
      location: {
        geolocation: 'Russia, Moscow, Aviamotornaya 69',
        id: 3,
        name: 'DataPro Moscow I (RU)',
        userspace: 2,
      },
      location_id: 3,
      mac: null,
      main_ipv4: 19367,
      main_ipv4_info: {
        domain: 'cs59019.com',
        first: 1e39,
        id: 19367,
        name: '94.198.51.220',
        temporary: 0,
      },
      main_ipv6: null,
      main_ipv6_info: {
        domain: null,
        first: null,
        id: null,
        name: null,
        temporary: null,
      },
      model: null,
      name: 'cs59019',
      nomenclature: '',
      note: '',
      operation: null,
      os_template: null,
      owner: {
        email: 'gamebrolive@gmail.com',
        id: 930,
      },
      owner_email: 'gamebrolive@gmail.com',
      pdu: null,
      pdu_connection: [
        {
          connection_id: 2795,
          identity: '20',
          pdu_id: 34,
          pdu_name: 'sm_m16_i13_pdu_1_e35331',
          port_id: 660,
          power_status: 'up',
        },
      ],
      platform: {
        id: 14,
        name: 'Colocation 1U',
        size: 1,
        type: 'server',
      },
      power_status: 'on',
      price: null,
      rack: {
        id: 21,
        name: 'DP-M16-I13',
        size: 48,
      },
      reserved_to_date: null,
      serial_number: null,
      server_profile_operation: null,
      settings: null,
      slot: null,
      state: 'ok',
      state_info: null,
      switch_connection: [
        {
          admin_status: 'up',
          connection_id: 5930,
          description: 'GigabitEthernet0/14',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 900,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 35,
          switch_name: 'DP.M16.RI13-sw-1_35563',
          vlan: {
            vlan_id: 1203,
            vlan_name: 'SmartApe_Dedic',
            vlan_owner: null,
          },
        },
      ],
      unit: 3,
      user_note: '',
      uuid: 'b6725b2d-2590-4f9d-83e4-c6efbf077f9b',
      warehouse: null,
      warehouse_status: 'in_rack',
      warehouse_status_info: null,
      warranty: null,
    },
    {
      barcode: 'cs59020',
      chassis: {
        id: null,
        name: null,
        server_slot_count: null,
        size: null,
        unit: null,
      },
      configuration: '',
      custom_configuration: null,
      diag_error: null,
      domain: 'cs59020.com',
      exploitation_status: 'in_exploitation',
      generated_configuration: '',
      has_errors: false,
      id: 3242,
      intel_amt: null,
      ip: [
        {
          domain: 'cs59020.com',
          family: 'ipv4',
          gateway: '94.198.51.254',
          id: 19368,
          name: '94.198.51.224',
          network: '94.198.51.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
        {
          domain: 'gamebrolive5.example.com',
          family: 'ipv4',
          gateway: '152.89.217.254',
          id: 19391,
          name: '152.89.217.166',
          network: '152.89.217.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
      ],
      ipmi: null,
      is_custom_configuration: false,
      is_new: false,
      location: {
        geolocation: 'Russia, Moscow, Aviamotornaya 69',
        id: 3,
        name: 'DataPro Moscow I (RU)',
        userspace: 2,
      },
      location_id: 3,
      mac: null,
      main_ipv4: 19368,
      main_ipv4_info: {
        domain: 'cs59020.com',
        first: 1e39,
        id: 19368,
        name: '94.198.51.224',
        temporary: 0,
      },
      main_ipv6: null,
      main_ipv6_info: {
        domain: null,
        first: null,
        id: null,
        name: null,
        temporary: null,
      },
      model: null,
      name: 'cs59020',
      nomenclature: '',
      note: '',
      operation: null,
      os_template: null,
      owner: {
        email: 'gamebrolive@gmail.com',
        id: 930,
      },
      owner_email: 'gamebrolive@gmail.com',
      pdu: null,
      pdu_connection: [],
      platform: {
        id: 14,
        name: 'Colocation 1U',
        size: 1,
        type: 'server',
      },
      power_status: 'unknown',
      price: null,
      rack: {
        id: 25,
        name: 'DP-M16-I17',
        size: 48,
      },
      reserved_to_date: null,
      serial_number: null,
      server_profile_operation: null,
      settings: null,
      slot: null,
      state: 'ok',
      state_info: null,
      switch_connection: [
        {
          admin_status: 'up',
          connection_id: 5894,
          description: 'GigabitEthernet1/0/12',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 1948,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 44,
          switch_name: 'DP.M16.RI17-sw-1_e39564',
          vlan: {
            vlan_id: 1203,
            vlan_name: 'SmartApe_Dedic',
            vlan_owner: null,
          },
        },
        {
          admin_status: 'up',
          connection_id: 5915,
          description: 'GigabitEthernet1/0/11',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 1947,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 44,
          switch_name: 'DP.M16.RI17-sw-1_e39564',
          vlan: {
            vlan_id: 1203,
            vlan_name: 'SmartApe_Dedic',
            vlan_owner: null,
          },
        },
      ],
      unit: 20,
      user_note: '',
      uuid: 'cc8cbc8b-4c69-45eb-8e5e-2a0f5ce756e8',
      warehouse: null,
      warehouse_status: 'in_rack',
      warehouse_status_info: null,
      warranty: null,
    },
    {
      barcode: 'cs59021',
      chassis: {
        id: null,
        name: null,
        server_slot_count: null,
        size: null,
        unit: null,
      },
      configuration: '',
      custom_configuration: null,
      diag_error: null,
      domain: 'cs59021.com',
      exploitation_status: 'in_exploitation',
      generated_configuration: '',
      has_errors: false,
      id: 3243,
      intel_amt: null,
      ip: [
        {
          domain: 'cs59021.com',
          family: 'ipv4',
          gateway: '94.198.55.254',
          id: 19369,
          name: '94.198.55.93',
          network: '94.198.55.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
        {
          domain: 'gamebrolive6.example.com',
          family: 'ipv4',
          gateway: '152.89.217.254',
          id: 19392,
          name: '152.89.217.174',
          network: '152.89.217.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
      ],
      ipmi: null,
      is_custom_configuration: false,
      is_new: false,
      location: {
        geolocation: 'Russia, Moscow, Aviamotornaya 69',
        id: 3,
        name: 'DataPro Moscow I (RU)',
        userspace: 2,
      },
      location_id: 3,
      mac: null,
      main_ipv4: 19369,
      main_ipv4_info: {
        domain: 'cs59021.com',
        first: 1e39,
        id: 19369,
        name: '94.198.55.93',
        temporary: 0,
      },
      main_ipv6: null,
      main_ipv6_info: {
        domain: null,
        first: null,
        id: null,
        name: null,
        temporary: null,
      },
      model: null,
      name: 'cs59021',
      nomenclature: '',
      note: '',
      operation: null,
      os_template: null,
      owner: {
        email: 'gamebrolive@gmail.com',
        id: 930,
      },
      owner_email: 'gamebrolive@gmail.com',
      pdu: null,
      pdu_connection: [],
      platform: {
        id: 14,
        name: 'Colocation 1U',
        size: 1,
        type: 'server',
      },
      power_status: 'unknown',
      price: null,
      rack: {
        id: 25,
        name: 'DP-M16-I17',
        size: 48,
      },
      reserved_to_date: null,
      serial_number: null,
      server_profile_operation: null,
      settings: null,
      slot: null,
      state: 'ok',
      state_info: null,
      switch_connection: [
        {
          admin_status: 'up',
          connection_id: 5934,
          description: 'GigabitEthernet1/0/8',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 1944,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 44,
          switch_name: 'DP.M16.RI17-sw-1_e39564',
          vlan: {
            vlan_id: 1203,
            vlan_name: 'SmartApe_Dedic',
            vlan_owner: null,
          },
        },
      ],
      unit: 15,
      user_note: '',
      uuid: '70e49360-3c6d-4718-a3d1-aafc5a68dcf4',
      warehouse: null,
      warehouse_status: 'in_rack',
      warehouse_status_info: null,
      warranty: null,
    },
    {
      barcode: 'cs59022',
      chassis: {
        id: null,
        name: null,
        server_slot_count: null,
        size: null,
        unit: null,
      },
      configuration: '',
      custom_configuration: null,
      diag_error: null,
      domain: 'cs59022.com',
      exploitation_status: 'in_exploitation',
      generated_configuration: '',
      has_errors: false,
      id: 3244,
      intel_amt: null,
      ip: [
        {
          domain: 'cs59022.com',
          family: 'ipv4',
          gateway: '94.198.55.254',
          id: 19370,
          name: '94.198.55.101',
          network: '94.198.55.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
        {
          domain: 'gamebrolive7.example.com',
          family: 'ipv4',
          gateway: '152.89.217.254',
          id: 19393,
          name: '152.89.217.175',
          network: '152.89.217.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
      ],
      ipmi: null,
      is_custom_configuration: false,
      is_new: false,
      location: {
        geolocation: 'Russia, Moscow, Aviamotornaya 69',
        id: 3,
        name: 'DataPro Moscow I (RU)',
        userspace: 2,
      },
      location_id: 3,
      mac: null,
      main_ipv4: 19370,
      main_ipv4_info: {
        domain: 'cs59022.com',
        first: 1e39,
        id: 19370,
        name: '94.198.55.101',
        temporary: 0,
      },
      main_ipv6: null,
      main_ipv6_info: {
        domain: null,
        first: null,
        id: null,
        name: null,
        temporary: null,
      },
      model: null,
      name: 'cs59022',
      nomenclature: '',
      note: '',
      operation: null,
      os_template: null,
      owner: {
        email: 'gamebrolive@gmail.com',
        id: 930,
      },
      owner_email: 'gamebrolive@gmail.com',
      pdu: null,
      pdu_connection: [],
      platform: {
        id: 14,
        name: 'Colocation 1U',
        size: 1,
        type: 'server',
      },
      power_status: 'unknown',
      price: null,
      rack: {
        id: 25,
        name: 'DP-M16-I17',
        size: 48,
      },
      reserved_to_date: null,
      serial_number: null,
      server_profile_operation: null,
      settings: null,
      slot: null,
      state: 'ok',
      state_info: null,
      switch_connection: [
        {
          admin_status: 'up',
          connection_id: 5897,
          description: 'GigabitEthernet1/0/20',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 1956,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 44,
          switch_name: 'DP.M16.RI17-sw-1_e39564',
          vlan: {
            vlan_id: 1203,
            vlan_name: 'SmartApe_Dedic',
            vlan_owner: null,
          },
        },
      ],
      unit: 12,
      user_note: '',
      uuid: 'b488e782-7526-4cfd-94a3-355322db6927',
      warehouse: null,
      warehouse_status: 'in_rack',
      warehouse_status_info: null,
      warranty: null,
    },
    {
      barcode: 'cs59023',
      chassis: {
        id: null,
        name: null,
        server_slot_count: null,
        size: null,
        unit: null,
      },
      configuration: '',
      custom_configuration: null,
      diag_error: null,
      domain: 'cs59023.com',
      exploitation_status: 'in_exploitation',
      generated_configuration: '',
      has_errors: false,
      id: 3245,
      intel_amt: null,
      ip: [
        {
          domain: 'cs59023.com',
          family: 'ipv4',
          gateway: '94.198.55.254',
          id: 19371,
          name: '94.198.55.107',
          network: '94.198.55.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
        {
          domain: 'gamebrolive8.example.com',
          family: 'ipv4',
          gateway: '152.89.217.254',
          id: 19394,
          name: '152.89.217.185',
          network: '152.89.217.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
      ],
      ipmi: null,
      is_custom_configuration: false,
      is_new: false,
      location: {
        geolocation: 'Russia, Moscow, Aviamotornaya 69',
        id: 3,
        name: 'DataPro Moscow I (RU)',
        userspace: 2,
      },
      location_id: 3,
      mac: null,
      main_ipv4: 19371,
      main_ipv4_info: {
        domain: 'cs59023.com',
        first: 1e39,
        id: 19371,
        name: '94.198.55.107',
        temporary: 0,
      },
      main_ipv6: null,
      main_ipv6_info: {
        domain: null,
        first: null,
        id: null,
        name: null,
        temporary: null,
      },
      model: null,
      name: 'cs59023',
      nomenclature: '',
      note: '',
      operation: null,
      os_template: null,
      owner: {
        email: 'gamebrolive@gmail.com',
        id: 930,
      },
      owner_email: 'gamebrolive@gmail.com',
      pdu: null,
      pdu_connection: [
        {
          connection_id: 2796,
          identity: '11',
          pdu_id: 37,
          pdu_name: 'DP.M16.RI17-pdu-1_e37202',
          port_id: 699,
          power_status: 'up',
        },
      ],
      platform: {
        id: 14,
        name: 'Colocation 1U',
        size: 1,
        type: 'server',
      },
      power_status: 'on',
      price: null,
      rack: {
        id: 25,
        name: 'DP-M16-I17',
        size: 48,
      },
      reserved_to_date: null,
      serial_number: null,
      server_profile_operation: null,
      settings: null,
      slot: null,
      state: 'ok',
      state_info: null,
      switch_connection: [
        {
          admin_status: 'up',
          connection_id: 5932,
          description: 'GigabitEthernet1/0/28',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 1964,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 44,
          switch_name: 'DP.M16.RI17-sw-1_e39564',
          vlan: {
            vlan_id: 1203,
            vlan_name: 'SmartApe_Dedic',
            vlan_owner: null,
          },
        },
      ],
      unit: 39,
      user_note: '',
      uuid: '1e559c99-5418-44b2-9580-e9b7e87ba077',
      warehouse: null,
      warehouse_status: 'in_rack',
      warehouse_status_info: null,
      warranty: null,
    },
    {
      barcode: 'cs59034',
      chassis: {
        id: null,
        name: null,
        server_slot_count: null,
        size: null,
        unit: null,
      },
      configuration: '',
      custom_configuration: null,
      diag_error: null,
      domain: 'cs59034.com',
      exploitation_status: 'in_exploitation',
      generated_configuration: '',
      has_errors: false,
      id: 3246,
      intel_amt: null,
      ip: [
        {
          domain: 'cs59034.com',
          family: 'ipv4',
          gateway: '94.198.55.254',
          id: 19372,
          name: '94.198.55.113',
          network: '94.198.55.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
        {
          domain: 'gamebrolive9.example.com',
          family: 'ipv4',
          gateway: '152.89.217.254',
          id: 19395,
          name: '152.89.217.199',
          network: '152.89.217.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
      ],
      ipmi: null,
      is_custom_configuration: false,
      is_new: false,
      location: {
        geolocation: 'Russia, Moscow, Aviamotornaya 69',
        id: 3,
        name: 'DataPro Moscow I (RU)',
        userspace: 2,
      },
      location_id: 3,
      mac: null,
      main_ipv4: 19372,
      main_ipv4_info: {
        domain: 'cs59034.com',
        first: 1e39,
        id: 19372,
        name: '94.198.55.113',
        temporary: 0,
      },
      main_ipv6: null,
      main_ipv6_info: {
        domain: null,
        first: null,
        id: null,
        name: null,
        temporary: null,
      },
      model: null,
      name: 'cs59034',
      nomenclature: '',
      note: '',
      operation: null,
      os_template: null,
      owner: {
        email: 'gamebrolive@gmail.com',
        id: 930,
      },
      owner_email: 'gamebrolive@gmail.com',
      pdu: null,
      pdu_connection: [
        {
          connection_id: 2797,
          identity: '15',
          pdu_id: 23,
          pdu_name: 'DP.M1.A07-pdu-2_25639',
          port_id: 487,
          power_status: 'up',
        },
      ],
      platform: {
        id: 14,
        name: 'Colocation 1U',
        size: 1,
        type: 'server',
      },
      power_status: 'on',
      price: null,
      rack: {
        id: 15,
        name: 'DP-M1-A07',
        size: 48,
      },
      reserved_to_date: null,
      serial_number: null,
      server_profile_operation: null,
      settings: null,
      slot: null,
      state: 'ok',
      state_info: null,
      switch_connection: [
        {
          admin_status: 'up',
          connection_id: 5899,
          description: 'GigabitEthernet1/0/32',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 518,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 23,
          switch_name: 'DP.M1.RA07-sw-1_22596',
          vlan: {
            vlan_id: 1203,
            vlan_name: 'SmartApe_Dedic',
            vlan_owner: null,
          },
        },
      ],
      unit: 23,
      user_note: '',
      uuid: '588a8f13-60ec-48f1-bb7b-a47d3ec30ef4',
      warehouse: null,
      warehouse_status: 'in_rack',
      warehouse_status_info: null,
      warranty: null,
    },
    {
      barcode: 'cs59035',
      chassis: {
        id: null,
        name: null,
        server_slot_count: null,
        size: null,
        unit: null,
      },
      configuration: '',
      custom_configuration: null,
      diag_error: null,
      domain: 'cs59035.com',
      exploitation_status: 'in_exploitation',
      generated_configuration: '',
      has_errors: false,
      id: 3247,
      intel_amt: null,
      ip: [
        {
          domain: 'cs59035.com',
          family: 'ipv4',
          gateway: '94.198.55.254',
          id: 19373,
          name: '94.198.55.124',
          network: '94.198.55.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
        {
          domain: 'gamebrolive10.example.com',
          family: 'ipv4',
          gateway: '152.89.217.254',
          id: 19396,
          name: '152.89.217.204',
          network: '152.89.217.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
      ],
      ipmi: null,
      is_custom_configuration: false,
      is_new: false,
      location: {
        geolocation: 'Russia, Moscow, Aviamotornaya 69',
        id: 3,
        name: 'DataPro Moscow I (RU)',
        userspace: 2,
      },
      location_id: 3,
      mac: null,
      main_ipv4: 19373,
      main_ipv4_info: {
        domain: 'cs59035.com',
        first: 1e39,
        id: 19373,
        name: '94.198.55.124',
        temporary: 0,
      },
      main_ipv6: null,
      main_ipv6_info: {
        domain: null,
        first: null,
        id: null,
        name: null,
        temporary: null,
      },
      model: null,
      name: 'cs59035',
      nomenclature: '',
      note: '',
      operation: null,
      os_template: null,
      owner: {
        email: 'gamebrolive@gmail.com',
        id: 930,
      },
      owner_email: 'gamebrolive@gmail.com',
      pdu: null,
      pdu_connection: [
        {
          connection_id: 2798,
          identity: '4',
          pdu_id: 23,
          pdu_name: 'DP.M1.A07-pdu-2_25639',
          port_id: 476,
          power_status: 'up',
        },
      ],
      platform: {
        id: 14,
        name: 'Colocation 1U',
        size: 1,
        type: 'server',
      },
      power_status: 'on',
      price: null,
      rack: {
        id: 15,
        name: 'DP-M1-A07',
        size: 48,
      },
      reserved_to_date: null,
      serial_number: null,
      server_profile_operation: null,
      settings: null,
      slot: null,
      state: 'ok',
      state_info: null,
      switch_connection: [
        {
          admin_status: 'up',
          connection_id: 5900,
          description: 'GigabitEthernet1/0/27',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 513,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 23,
          switch_name: 'DP.M1.RA07-sw-1_22596',
          vlan: {
            vlan_id: 1203,
            vlan_name: 'SmartApe_Dedic',
            vlan_owner: null,
          },
        },
      ],
      unit: 19,
      user_note: '',
      uuid: '29432d2b-e5b7-4686-9d2d-5dd9a61ec035',
      warehouse: null,
      warehouse_status: 'in_rack',
      warehouse_status_info: null,
      warranty: null,
    },
    {
      barcode: 'cs59036',
      chassis: {
        id: null,
        name: null,
        server_slot_count: null,
        size: null,
        unit: null,
      },
      configuration: '',
      custom_configuration: null,
      diag_error: null,
      domain: 'cs59036.com',
      exploitation_status: 'in_exploitation',
      generated_configuration: '',
      has_errors: false,
      id: 3248,
      intel_amt: null,
      ip: [
        {
          domain: 'cs59036.com',
          family: 'ipv4',
          gateway: '94.198.55.254',
          id: 19374,
          name: '94.198.55.200',
          network: '94.198.55.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
        {
          domain: 'gamebrolive11.example.com',
          family: 'ipv4',
          gateway: '152.89.217.254',
          id: 19397,
          name: '152.89.217.219',
          network: '152.89.217.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
      ],
      ipmi: null,
      is_custom_configuration: false,
      is_new: false,
      location: {
        geolocation: 'Russia, Moscow, Aviamotornaya 69',
        id: 3,
        name: 'DataPro Moscow I (RU)',
        userspace: 2,
      },
      location_id: 3,
      mac: null,
      main_ipv4: 19374,
      main_ipv4_info: {
        domain: 'cs59036.com',
        first: 1e39,
        id: 19374,
        name: '94.198.55.200',
        temporary: 0,
      },
      main_ipv6: null,
      main_ipv6_info: {
        domain: null,
        first: null,
        id: null,
        name: null,
        temporary: null,
      },
      model: null,
      name: 'cs59036',
      nomenclature: '',
      note: '',
      operation: null,
      os_template: null,
      owner: {
        email: 'gamebrolive@gmail.com',
        id: 930,
      },
      owner_email: 'gamebrolive@gmail.com',
      pdu: null,
      pdu_connection: [
        {
          connection_id: 2813,
          identity: '14',
          pdu_id: 13,
          pdu_name: 'DP.M1.B18-pdu-2_26092',
          port_id: 286,
          power_status: 'up',
        },
      ],
      platform: {
        id: 14,
        name: 'Colocation 1U',
        size: 1,
        type: 'server',
      },
      power_status: 'on',
      price: null,
      rack: {
        id: 7,
        name: 'DP-M1-B18',
        size: 48,
      },
      reserved_to_date: null,
      serial_number: null,
      server_profile_operation: null,
      settings: null,
      slot: null,
      state: 'ok',
      state_info: null,
      switch_connection: [
        {
          admin_status: 'up',
          connection_id: 5901,
          description: 'FastEthernet0/31',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 1617,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 9,
          switch_name: 'DP.M1.RB18-sw-1_27257',
          vlan: {
            vlan_id: 1203,
            vlan_name: 'SmartApe_Dedic',
            vlan_owner: null,
          },
        },
      ],
      unit: 45,
      user_note: '',
      uuid: '2431661c-0fc2-42a9-b71b-9779644adf2f',
      warehouse: null,
      warehouse_status: 'in_rack',
      warehouse_status_info: null,
      warranty: null,
    },
    {
      barcode: 'cs59037',
      chassis: {
        id: null,
        name: null,
        server_slot_count: null,
        size: null,
        unit: null,
      },
      configuration: '',
      custom_configuration: null,
      diag_error: null,
      domain: 'cs59037.com',
      exploitation_status: 'in_exploitation',
      generated_configuration: '',
      has_errors: false,
      id: 3249,
      intel_amt: null,
      ip: [
        {
          domain: 'cs59037.com',
          family: 'ipv4',
          gateway: '94.198.55.254',
          id: 19375,
          name: '94.198.55.237',
          network: '94.198.55.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
        {
          domain: 'gamebrolive12.example.com',
          family: 'ipv4',
          gateway: '152.89.217.254',
          id: 19398,
          name: '152.89.217.220',
          network: '152.89.217.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
      ],
      ipmi: null,
      is_custom_configuration: false,
      is_new: false,
      location: {
        geolocation: 'Russia, Moscow, Aviamotornaya 69',
        id: 3,
        name: 'DataPro Moscow I (RU)',
        userspace: 2,
      },
      location_id: 3,
      mac: null,
      main_ipv4: 19375,
      main_ipv4_info: {
        domain: 'cs59037.com',
        first: 1e39,
        id: 19375,
        name: '94.198.55.237',
        temporary: 0,
      },
      main_ipv6: null,
      main_ipv6_info: {
        domain: null,
        first: null,
        id: null,
        name: null,
        temporary: null,
      },
      model: null,
      name: 'cs59037',
      nomenclature: '',
      note: '',
      operation: null,
      os_template: null,
      owner: {
        email: 'gamebrolive@gmail.com',
        id: 930,
      },
      owner_email: 'gamebrolive@gmail.com',
      pdu: null,
      pdu_connection: [
        {
          connection_id: 2799,
          identity: '16',
          pdu_id: 14,
          pdu_name: 'DP.M1.B18-pdu-1_26439',
          port_id: 304,
          power_status: 'up',
        },
      ],
      platform: {
        id: 14,
        name: 'Colocation 1U',
        size: 1,
        type: 'server',
      },
      power_status: 'on',
      price: null,
      rack: {
        id: 7,
        name: 'DP-M1-B18',
        size: 48,
      },
      reserved_to_date: null,
      serial_number: null,
      server_profile_operation: null,
      settings: null,
      slot: null,
      state: 'ok',
      state_info: null,
      switch_connection: [
        {
          admin_status: 'up',
          connection_id: 5902,
          description: 'FastEthernet0/45',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 1631,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 9,
          switch_name: 'DP.M1.RB18-sw-1_27257',
          vlan: {
            vlan_id: 1203,
            vlan_name: 'SmartApe_Dedic',
            vlan_owner: null,
          },
        },
      ],
      unit: 46,
      user_note: '',
      uuid: 'ca1ce0b7-3d49-45e3-be94-cef062d3d76b',
      warehouse: null,
      warehouse_status: 'in_rack',
      warehouse_status_info: null,
      warranty: null,
    },
    {
      barcode: 'cs59031',
      chassis: {
        id: null,
        name: null,
        server_slot_count: null,
        size: null,
        unit: null,
      },
      configuration: '',
      custom_configuration: null,
      diag_error: null,
      domain: 'cs59031.com',
      exploitation_status: 'in_exploitation',
      generated_configuration: '',
      has_errors: false,
      id: 3250,
      intel_amt: null,
      ip: [
        {
          domain: 'cs59031.com',
          family: 'ipv4',
          gateway: '152.89.216.254',
          id: 19376,
          name: '152.89.216.27',
          network: '152.89.216.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
        {
          domain: 'gamebrolive13.example.com',
          family: 'ipv4',
          gateway: '152.89.217.254',
          id: 19399,
          name: '152.89.217.238',
          network: '152.89.217.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
      ],
      ipmi: null,
      is_custom_configuration: false,
      is_new: false,
      location: {
        geolocation: 'Russia, Moscow, Aviamotornaya 69',
        id: 3,
        name: 'DataPro Moscow I (RU)',
        userspace: 2,
      },
      location_id: 3,
      mac: null,
      main_ipv4: 19376,
      main_ipv4_info: {
        domain: 'cs59031.com',
        first: 1e39,
        id: 19376,
        name: '152.89.216.27',
        temporary: 0,
      },
      main_ipv6: null,
      main_ipv6_info: {
        domain: null,
        first: null,
        id: null,
        name: null,
        temporary: null,
      },
      model: null,
      name: 'cs59031',
      nomenclature: '',
      note: '',
      operation: null,
      os_template: null,
      owner: {
        email: 'gamebrolive@gmail.com',
        id: 930,
      },
      owner_email: 'gamebrolive@gmail.com',
      pdu: null,
      pdu_connection: [
        {
          connection_id: 2800,
          identity: '14',
          pdu_id: 38,
          pdu_name: 'DP.M1.RC14-pdu-1_37200',
          port_id: 726,
          power_status: 'up',
        },
      ],
      platform: {
        id: 14,
        name: 'Colocation 1U',
        size: 1,
        type: 'server',
      },
      power_status: 'on',
      price: null,
      rack: {
        id: 3,
        name: 'DP-M1-C14',
        size: 48,
      },
      reserved_to_date: null,
      serial_number: null,
      server_profile_operation: null,
      settings: null,
      slot: null,
      state: 'ok',
      state_info: null,
      switch_connection: [
        {
          admin_status: 'up',
          connection_id: 5916,
          description: 'GigabitEthernet1/0/35',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 1319,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 46,
          switch_name: 'DP.M1.RC14-sw-1_e40080',
          vlan: {
            vlan_id: 413,
            vlan_name: 'VLAN0413',
            vlan_owner: null,
          },
        },
        {
          admin_status: 'up',
          connection_id: 5921,
          description: 'GigabitEthernet1/0/2',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 1286,
          is_ipmi_connection: 0,
          oper_status: 'down',
          switch: 46,
          switch_name: 'DP.M1.RC14-sw-1_e40080',
          vlan: {
            vlan_id: 1203,
            vlan_name: 'SmartApe_Dedic',
            vlan_owner: null,
          },
        },
      ],
      unit: 35,
      user_note: '',
      uuid: 'fba3068c-8f40-408a-bae6-f27244fd58b0',
      warehouse: null,
      warehouse_status: 'in_rack',
      warehouse_status_info: null,
      warranty: null,
    },
    {
      barcode: 'cs59032',
      chassis: {
        id: null,
        name: null,
        server_slot_count: null,
        size: null,
        unit: null,
      },
      configuration: '',
      custom_configuration: null,
      diag_error: null,
      domain: 'cs59032.com',
      exploitation_status: 'in_exploitation',
      generated_configuration: '',
      has_errors: false,
      id: 3251,
      intel_amt: null,
      ip: [
        {
          domain: 'cs59032.com',
          family: 'ipv4',
          gateway: '152.89.216.254',
          id: 19377,
          name: '152.89.216.41',
          network: '152.89.216.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
        {
          domain: 'gamebrolive14.example.com',
          family: 'ipv4',
          gateway: '152.89.217.254',
          id: 19400,
          name: '152.89.217.249',
          network: '152.89.217.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
      ],
      ipmi: null,
      is_custom_configuration: false,
      is_new: false,
      location: {
        geolocation: 'Russia, Moscow, Aviamotornaya 69',
        id: 3,
        name: 'DataPro Moscow I (RU)',
        userspace: 2,
      },
      location_id: 3,
      mac: null,
      main_ipv4: 19377,
      main_ipv4_info: {
        domain: 'cs59032.com',
        first: 1e39,
        id: 19377,
        name: '152.89.216.41',
        temporary: 0,
      },
      main_ipv6: null,
      main_ipv6_info: {
        domain: null,
        first: null,
        id: null,
        name: null,
        temporary: null,
      },
      model: null,
      name: 'cs59032',
      nomenclature: '',
      note: '',
      operation: null,
      os_template: null,
      owner: {
        email: 'gamebrolive@gmail.com',
        id: 930,
      },
      owner_email: 'gamebrolive@gmail.com',
      pdu: null,
      pdu_connection: [
        {
          connection_id: 2801,
          identity: '11',
          pdu_id: 38,
          pdu_name: 'DP.M1.RC14-pdu-1_37200',
          port_id: 723,
          power_status: 'up',
        },
      ],
      platform: {
        id: 14,
        name: 'Colocation 1U',
        size: 1,
        type: 'server',
      },
      power_status: 'on',
      price: null,
      rack: {
        id: 3,
        name: 'DP-M1-C14',
        size: 48,
      },
      reserved_to_date: null,
      serial_number: null,
      server_profile_operation: null,
      settings: null,
      slot: null,
      state: 'ok',
      state_info: null,
      switch_connection: [
        {
          admin_status: 'up',
          connection_id: 5922,
          description: 'GigabitEthernet1/0/18',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 1302,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 46,
          switch_name: 'DP.M1.RC14-sw-1_e40080',
          vlan: {
            vlan_id: 1203,
            vlan_name: 'SmartApe_Dedic',
            vlan_owner: null,
          },
        },
      ],
      unit: 36,
      user_note: '',
      uuid: '420b3492-7a56-45af-99f8-441bef3cb153',
      warehouse: null,
      warehouse_status: 'in_rack',
      warehouse_status_info: null,
      warranty: null,
    },
    {
      barcode: 'cs59033',
      chassis: {
        id: null,
        name: null,
        server_slot_count: null,
        size: null,
        unit: null,
      },
      configuration: '',
      custom_configuration: null,
      diag_error: null,
      domain: 'cs59033.com',
      exploitation_status: 'in_exploitation',
      generated_configuration: '',
      has_errors: false,
      id: 3252,
      intel_amt: null,
      ip: [
        {
          domain: 'cs59033.com',
          family: 'ipv4',
          gateway: '152.89.216.254',
          id: 19378,
          name: '152.89.216.80',
          network: '152.89.216.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
        {
          domain: 'gamebrolive15.example.com',
          family: 'ipv4',
          gateway: '152.89.217.254',
          id: 19401,
          name: '152.89.217.251',
          network: '152.89.217.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
      ],
      ipmi: null,
      is_custom_configuration: false,
      is_new: false,
      location: {
        geolocation: 'Russia, Moscow, Aviamotornaya 69',
        id: 3,
        name: 'DataPro Moscow I (RU)',
        userspace: 2,
      },
      location_id: 3,
      mac: null,
      main_ipv4: 19378,
      main_ipv4_info: {
        domain: 'cs59033.com',
        first: 1e39,
        id: 19378,
        name: '152.89.216.80',
        temporary: 0,
      },
      main_ipv6: null,
      main_ipv6_info: {
        domain: null,
        first: null,
        id: null,
        name: null,
        temporary: null,
      },
      model: null,
      name: 'cs59033',
      nomenclature: '',
      note: '',
      operation: null,
      os_template: null,
      owner: {
        email: 'gamebrolive@gmail.com',
        id: 930,
      },
      owner_email: 'gamebrolive@gmail.com',
      pdu: null,
      pdu_connection: [
        {
          connection_id: 2802,
          identity: '2',
          pdu_id: 38,
          pdu_name: 'DP.M1.RC14-pdu-1_37200',
          port_id: 714,
          power_status: 'up',
        },
      ],
      platform: {
        id: 14,
        name: 'Colocation 1U',
        size: 1,
        type: 'server',
      },
      power_status: 'on',
      price: null,
      rack: {
        id: 3,
        name: 'DP-M1-C14',
        size: 48,
      },
      reserved_to_date: null,
      serial_number: null,
      server_profile_operation: null,
      settings: null,
      slot: null,
      state: 'ok',
      state_info: null,
      switch_connection: [
        {
          admin_status: 'up',
          connection_id: 5935,
          description: 'GigabitEthernet1/0/20',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 1304,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 46,
          switch_name: 'DP.M1.RC14-sw-1_e40080',
          vlan: {
            vlan_id: 1203,
            vlan_name: 'SmartApe_Dedic',
            vlan_owner: null,
          },
        },
      ],
      unit: 14,
      user_note: '',
      uuid: 'a1f0b827-7f85-49bb-9640-6e96cf1c4400',
      warehouse: null,
      warehouse_status: 'in_rack',
      warehouse_status_info: null,
      warranty: null,
    },
    {
      barcode: 'cs59027',
      chassis: {
        id: null,
        name: null,
        server_slot_count: null,
        size: null,
        unit: null,
      },
      configuration: '',
      custom_configuration: null,
      diag_error: null,
      domain: 'cs59027.com',
      exploitation_status: 'in_exploitation',
      generated_configuration: '',
      has_errors: false,
      id: 3253,
      intel_amt: null,
      ip: [
        {
          domain: 'cs59027.com',
          family: 'ipv4',
          gateway: '152.89.216.254',
          id: 19379,
          name: '152.89.216.128',
          network: '152.89.216.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
        {
          domain: 'gamebrolive16.example.com',
          family: 'ipv4',
          gateway: '152.89.219.254',
          id: 19402,
          name: '152.89.219.9',
          network: '152.89.219.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
      ],
      ipmi: null,
      is_custom_configuration: false,
      is_new: false,
      location: {
        geolocation: 'Russia, Moscow, Aviamotornaya 69',
        id: 3,
        name: 'DataPro Moscow I (RU)',
        userspace: 2,
      },
      location_id: 3,
      mac: null,
      main_ipv4: 19379,
      main_ipv4_info: {
        domain: 'cs59027.com',
        first: 1e39,
        id: 19379,
        name: '152.89.216.128',
        temporary: 0,
      },
      main_ipv6: null,
      main_ipv6_info: {
        domain: null,
        first: null,
        id: null,
        name: null,
        temporary: null,
      },
      model: null,
      name: 'cs59027',
      nomenclature: '',
      note: '',
      operation: null,
      os_template: null,
      owner: {
        email: 'gamebrolive@gmail.com',
        id: 930,
      },
      owner_email: 'gamebrolive@gmail.com',
      pdu: null,
      pdu_connection: [
        {
          connection_id: 2803,
          identity: '11',
          pdu_id: 28,
          pdu_name: 'DP.M1.RE09-pdu-2_e33736',
          port_id: 579,
          power_status: 'up',
        },
      ],
      platform: {
        id: 14,
        name: 'Colocation 1U',
        size: 1,
        type: 'server',
      },
      power_status: 'on',
      price: null,
      rack: {
        id: 19,
        name: 'DP-M1-E09',
        size: 48,
      },
      reserved_to_date: null,
      serial_number: null,
      server_profile_operation: null,
      settings: null,
      slot: null,
      state: 'ok',
      state_info: null,
      switch_connection: [
        {
          admin_status: 'up',
          connection_id: 5917,
          description: 'GigabitEthernet0/16',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 804,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 31,
          switch_name: 'DP.M1.RE09-sw-1_e34049',
          vlan: {
            vlan_id: 1203,
            vlan_name: 'SmartApe_Dedic',
            vlan_owner: null,
          },
        },
        {
          admin_status: 'up',
          connection_id: 5923,
          description: 'GigabitEthernet0/8',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 796,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 31,
          switch_name: 'DP.M1.RE09-sw-1_e34049',
          vlan: {
            vlan_id: 1203,
            vlan_name: 'SmartApe_Dedic',
            vlan_owner: null,
          },
        },
      ],
      unit: 32,
      user_note: '',
      uuid: '07744601-9718-4e06-b0b4-8fe217d9d44e',
      warehouse: null,
      warehouse_status: 'in_rack',
      warehouse_status_info: null,
      warranty: null,
    },
    {
      barcode: 'cs59025',
      chassis: {
        id: null,
        name: null,
        server_slot_count: null,
        size: null,
        unit: null,
      },
      configuration: '',
      custom_configuration: null,
      diag_error: null,
      domain: 'cs59025.com',
      exploitation_status: 'in_exploitation',
      generated_configuration: '',
      has_errors: false,
      id: 3254,
      intel_amt: null,
      ip: [
        {
          domain: 'cs59025.com',
          family: 'ipv4',
          gateway: '152.89.216.254',
          id: 19380,
          name: '152.89.216.143',
          network: '152.89.216.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
        {
          domain: 'gamebrolive17.example.com',
          family: 'ipv4',
          gateway: '152.89.219.254',
          id: 19403,
          name: '152.89.219.10',
          network: '152.89.219.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
      ],
      ipmi: null,
      is_custom_configuration: false,
      is_new: false,
      location: {
        geolocation: 'Russia, Moscow, Aviamotornaya 69',
        id: 3,
        name: 'DataPro Moscow I (RU)',
        userspace: 2,
      },
      location_id: 3,
      mac: null,
      main_ipv4: 19380,
      main_ipv4_info: {
        domain: 'cs59025.com',
        first: 1e39,
        id: 19380,
        name: '152.89.216.143',
        temporary: 0,
      },
      main_ipv6: null,
      main_ipv6_info: {
        domain: null,
        first: null,
        id: null,
        name: null,
        temporary: null,
      },
      model: null,
      name: 'cs59025',
      nomenclature: '',
      note: '',
      operation: null,
      os_template: null,
      owner: {
        email: 'gamebrolive@gmail.com',
        id: 930,
      },
      owner_email: 'gamebrolive@gmail.com',
      pdu: null,
      pdu_connection: [
        {
          connection_id: 2805,
          identity: '9',
          pdu_id: 19,
          pdu_name: 'sm_e18_pdu_1_21440',
          port_id: 409,
          power_status: 'up',
        },
        {
          connection_id: 2804,
          identity: '16',
          pdu_id: 20,
          pdu_name: 'sm_e18_pdu_2_21439',
          port_id: 440,
          power_status: 'up',
        },
      ],
      platform: {
        id: 14,
        name: 'Colocation 1U',
        size: 1,
        type: 'server',
      },
      power_status: 'on',
      price: null,
      rack: {
        id: 13,
        name: 'DP-M1-E18',
        size: 48,
      },
      reserved_to_date: null,
      serial_number: null,
      server_profile_operation: null,
      settings: null,
      slot: null,
      state: 'ok',
      state_info: null,
      switch_connection: [
        {
          admin_status: 'up',
          connection_id: 5925,
          description: 'GigabitEthernet0/27',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 317,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 19,
          switch_name: 'DP.M1.RE18-sw-1_21597',
          vlan: {
            vlan_id: 1203,
            vlan_name: 'SmartApe_Dedic',
            vlan_owner: null,
          },
        },
      ],
      unit: 22,
      user_note: '',
      uuid: '2a4cee68-89e3-46c8-b8e2-f667fe10b24f',
      warehouse: null,
      warehouse_status: 'in_rack',
      warehouse_status_info: null,
      warranty: null,
    },
    {
      barcode: 'cs59026',
      chassis: {
        id: null,
        name: null,
        server_slot_count: null,
        size: null,
        unit: null,
      },
      configuration: '',
      custom_configuration: null,
      diag_error: null,
      domain: 'cs59026.com',
      exploitation_status: 'in_exploitation',
      generated_configuration: '',
      has_errors: false,
      id: 3255,
      intel_amt: null,
      ip: [
        {
          domain: 'cs59026.com',
          family: 'ipv4',
          gateway: '152.89.216.254',
          id: 19381,
          name: '152.89.216.206',
          network: '152.89.216.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
        {
          domain: 'gamebrolive18.example.com',
          family: 'ipv4',
          gateway: '152.89.219.254',
          id: 19404,
          name: '152.89.219.14',
          network: '152.89.219.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
      ],
      ipmi: null,
      is_custom_configuration: false,
      is_new: false,
      location: {
        geolocation: 'Russia, Moscow, Aviamotornaya 69',
        id: 3,
        name: 'DataPro Moscow I (RU)',
        userspace: 2,
      },
      location_id: 3,
      mac: null,
      main_ipv4: 19381,
      main_ipv4_info: {
        domain: 'cs59026.com',
        first: 1e39,
        id: 19381,
        name: '152.89.216.206',
        temporary: 0,
      },
      main_ipv6: null,
      main_ipv6_info: {
        domain: null,
        first: null,
        id: null,
        name: null,
        temporary: null,
      },
      model: null,
      name: 'cs59026',
      nomenclature: '',
      note: '',
      operation: null,
      os_template: null,
      owner: {
        email: 'gamebrolive@gmail.com',
        id: 930,
      },
      owner_email: 'gamebrolive@gmail.com',
      pdu: null,
      pdu_connection: [
        {
          connection_id: 2806,
          identity: '13',
          pdu_id: 19,
          pdu_name: 'sm_e18_pdu_1_21440',
          port_id: 413,
          power_status: 'up',
        },
        {
          connection_id: 2807,
          identity: '17',
          pdu_id: 20,
          pdu_name: 'sm_e18_pdu_2_21439',
          port_id: 441,
          power_status: 'up',
        },
      ],
      platform: {
        id: 14,
        name: 'Colocation 1U',
        size: 1,
        type: 'server',
      },
      power_status: 'on',
      price: null,
      rack: {
        id: 13,
        name: 'DP-M1-E18',
        size: 48,
      },
      reserved_to_date: null,
      serial_number: null,
      server_profile_operation: null,
      settings: null,
      slot: null,
      state: 'ok',
      state_info: null,
      switch_connection: [
        {
          admin_status: 'up',
          connection_id: 5908,
          description: 'GigabitEthernet0/33',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 323,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 19,
          switch_name: 'DP.M1.RE18-sw-1_21597',
          vlan: {
            vlan_id: 1203,
            vlan_name: 'SmartApe_Dedic',
            vlan_owner: null,
          },
        },
      ],
      unit: 26,
      user_note: '',
      uuid: '277d7d7f-d73e-47e4-afa5-e9ddff5e113b',
      warehouse: null,
      warehouse_status: 'in_rack',
      warehouse_status_info: null,
      warranty: null,
    },
    {
      barcode: 'cs59028',
      chassis: {
        id: null,
        name: null,
        server_slot_count: null,
        size: null,
        unit: null,
      },
      configuration: '',
      custom_configuration: null,
      diag_error: null,
      domain: 'cs59028.com',
      exploitation_status: 'in_exploitation',
      generated_configuration: '',
      has_errors: false,
      id: 3256,
      intel_amt: null,
      ip: [
        {
          domain: 'cs59028.com',
          family: 'ipv4',
          gateway: '152.89.217.254',
          id: 19382,
          name: '152.89.217.21',
          network: '152.89.217.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
        {
          domain: 'gamebrolive19.example.com',
          family: 'ipv4',
          gateway: '152.89.219.254',
          id: 19405,
          name: '152.89.219.16',
          network: '152.89.219.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
      ],
      ipmi: null,
      is_custom_configuration: false,
      is_new: false,
      location: {
        geolocation: 'Russia, Moscow, Aviamotornaya 69',
        id: 3,
        name: 'DataPro Moscow I (RU)',
        userspace: 2,
      },
      location_id: 3,
      mac: null,
      main_ipv4: 19382,
      main_ipv4_info: {
        domain: 'cs59028.com',
        first: 1e39,
        id: 19382,
        name: '152.89.217.21',
        temporary: 0,
      },
      main_ipv6: null,
      main_ipv6_info: {
        domain: null,
        first: null,
        id: null,
        name: null,
        temporary: null,
      },
      model: null,
      name: 'cs59028',
      nomenclature: '',
      note: '',
      operation: null,
      os_template: null,
      owner: {
        email: 'gamebrolive@gmail.com',
        id: 930,
      },
      owner_email: 'gamebrolive@gmail.com',
      pdu: null,
      pdu_connection: [
        {
          connection_id: 2808,
          identity: '14',
          pdu_id: 19,
          pdu_name: 'sm_e18_pdu_1_21440',
          port_id: 414,
          power_status: 'up',
        },
      ],
      platform: {
        id: 14,
        name: 'Colocation 1U',
        size: 1,
        type: 'server',
      },
      power_status: 'on',
      price: null,
      rack: {
        id: 13,
        name: 'DP-M1-E18',
        size: 48,
      },
      reserved_to_date: null,
      serial_number: null,
      server_profile_operation: null,
      settings: null,
      slot: null,
      state: 'ok',
      state_info: null,
      switch_connection: [
        {
          admin_status: 'up',
          connection_id: 5909,
          description: 'GigabitEthernet0/24',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 314,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 19,
          switch_name: 'DP.M1.RE18-sw-1_21597',
          vlan: {
            vlan_id: 1203,
            vlan_name: 'SmartApe_Dedic',
            vlan_owner: null,
          },
        },
        {
          admin_status: 'up',
          connection_id: 5918,
          description: 'GigabitEthernet0/21',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 311,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 19,
          switch_name: 'DP.M1.RE18-sw-1_21597',
          vlan: {
            vlan_id: 1,
            vlan_name: 'default',
            vlan_owner: null,
          },
        },
      ],
      unit: 28,
      user_note: '',
      uuid: '60d1abc5-9e07-4ee6-b5ef-5fad6f3c2c0d',
      warehouse: null,
      warehouse_status: 'in_rack',
      warehouse_status_info: null,
      warranty: null,
    },
    {
      barcode: 'cs59029',
      chassis: {
        id: null,
        name: null,
        server_slot_count: null,
        size: null,
        unit: null,
      },
      configuration: '',
      custom_configuration: null,
      diag_error: null,
      domain: 'cs59029.com',
      exploitation_status: 'in_exploitation',
      generated_configuration: '',
      has_errors: false,
      id: 3257,
      intel_amt: null,
      ip: [
        {
          domain: 'cs59029.com',
          family: 'ipv4',
          gateway: '152.89.217.254',
          id: 19383,
          name: '152.89.217.56',
          network: '152.89.217.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
        {
          domain: 'gamebrolive20.example.com',
          family: 'ipv4',
          gateway: '152.89.219.254',
          id: 19406,
          name: '152.89.219.35',
          network: '152.89.219.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
      ],
      ipmi: null,
      is_custom_configuration: false,
      is_new: false,
      location: {
        geolocation: 'Russia, Moscow, Aviamotornaya 69',
        id: 3,
        name: 'DataPro Moscow I (RU)',
        userspace: 2,
      },
      location_id: 3,
      mac: null,
      main_ipv4: 19383,
      main_ipv4_info: {
        domain: 'cs59029.com',
        first: 1e39,
        id: 19383,
        name: '152.89.217.56',
        temporary: 0,
      },
      main_ipv6: null,
      main_ipv6_info: {
        domain: null,
        first: null,
        id: null,
        name: null,
        temporary: null,
      },
      model: null,
      name: 'cs59029',
      nomenclature: '',
      note: '',
      operation: null,
      os_template: null,
      owner: {
        email: 'gamebrolive@gmail.com',
        id: 930,
      },
      owner_email: 'gamebrolive@gmail.com',
      pdu: null,
      pdu_connection: [
        {
          connection_id: 2809,
          identity: '15',
          pdu_id: 19,
          pdu_name: 'sm_e18_pdu_1_21440',
          port_id: 415,
          power_status: 'up',
        },
        {
          connection_id: 2810,
          identity: '15',
          pdu_id: 20,
          pdu_name: 'sm_e18_pdu_2_21439',
          port_id: 439,
          power_status: 'up',
        },
      ],
      platform: {
        id: 14,
        name: 'Colocation 1U',
        size: 1,
        type: 'server',
      },
      power_status: 'on',
      price: null,
      rack: {
        id: 13,
        name: 'DP-M1-E18',
        size: 48,
      },
      reserved_to_date: null,
      serial_number: null,
      server_profile_operation: null,
      settings: null,
      slot: null,
      state: 'ok',
      state_info: null,
      switch_connection: [
        {
          admin_status: 'up',
          connection_id: 5910,
          description: 'GigabitEthernet0/17',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 307,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 19,
          switch_name: 'DP.M1.RE18-sw-1_21597',
          vlan: {
            vlan_id: 1203,
            vlan_name: 'SmartApe_Dedic',
            vlan_owner: null,
          },
        },
        {
          admin_status: 'up',
          connection_id: 5919,
          description: 'GigabitEthernet0/38',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 328,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 19,
          switch_name: 'DP.M1.RE18-sw-1_21597',
          vlan: {
            vlan_id: 1,
            vlan_name: 'default',
            vlan_owner: null,
          },
        },
      ],
      unit: 29,
      user_note: '',
      uuid: '02ce1df0-857d-4580-be36-193aadec3639',
      warehouse: null,
      warehouse_status: 'in_rack',
      warehouse_status_info: null,
      warranty: null,
    },
    {
      barcode: 'cs59030',
      chassis: {
        id: null,
        name: null,
        server_slot_count: null,
        size: null,
        unit: null,
      },
      configuration: '',
      custom_configuration: null,
      diag_error: null,
      domain: 'cs59030.com',
      exploitation_status: 'in_exploitation',
      generated_configuration: '',
      has_errors: false,
      id: 3258,
      intel_amt: null,
      ip: [
        {
          domain: 'cs59030.com',
          family: 'ipv4',
          gateway: '152.89.217.254',
          id: 19384,
          name: '152.89.217.76',
          network: '152.89.217.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
        {
          domain: 'gamebrolive21.example.com',
          family: 'ipv4',
          gateway: '152.89.219.254',
          id: 19407,
          name: '152.89.219.67',
          network: '152.89.219.0/24',
          status: 'ok',
          status_info: null,
          temporary: 0,
          type: 'common',
          vpu_net: null,
          vpu_vlan: null,
        },
      ],
      ipmi: null,
      is_custom_configuration: false,
      is_new: false,
      location: {
        geolocation: 'Russia, Moscow, Aviamotornaya 69',
        id: 3,
        name: 'DataPro Moscow I (RU)',
        userspace: 2,
      },
      location_id: 3,
      mac: null,
      main_ipv4: 19384,
      main_ipv4_info: {
        domain: 'cs59030.com',
        first: 1e39,
        id: 19384,
        name: '152.89.217.76',
        temporary: 0,
      },
      main_ipv6: null,
      main_ipv6_info: {
        domain: null,
        first: null,
        id: null,
        name: null,
        temporary: null,
      },
      model: null,
      name: 'cs59030',
      nomenclature: '',
      note: '',
      operation: null,
      os_template: null,
      owner: {
        email: 'gamebrolive@gmail.com',
        id: 930,
      },
      owner_email: 'gamebrolive@gmail.com',
      pdu: null,
      pdu_connection: [
        {
          connection_id: 2812,
          identity: '23',
          pdu_id: 19,
          pdu_name: 'sm_e18_pdu_1_21440',
          port_id: 423,
          power_status: 'up',
        },
        {
          connection_id: 2811,
          identity: '21',
          pdu_id: 20,
          pdu_name: 'sm_e18_pdu_2_21439',
          port_id: 445,
          power_status: 'up',
        },
      ],
      platform: {
        id: 14,
        name: 'Colocation 1U',
        size: 1,
        type: 'server',
      },
      power_status: 'on',
      price: null,
      rack: {
        id: 13,
        name: 'DP-M1-E18',
        size: 48,
      },
      reserved_to_date: null,
      serial_number: null,
      server_profile_operation: null,
      settings: null,
      slot: null,
      state: 'ok',
      state_info: null,
      switch_connection: [
        {
          admin_status: 'up',
          connection_id: 5911,
          description: 'GigabitEthernet0/18',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 308,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 19,
          switch_name: 'DP.M1.RE18-sw-1_21597',
          vlan: {
            vlan_id: 1203,
            vlan_name: 'SmartApe_Dedic',
            vlan_owner: null,
          },
        },
        {
          admin_status: 'up',
          connection_id: 5920,
          description: 'GigabitEthernet0/9',
          do_not_collect_traffic: 0,
          hidden_connection: false,
          id: 299,
          is_ipmi_connection: 0,
          oper_status: 'up',
          switch: 19,
          switch_name: 'DP.M1.RE18-sw-1_21597',
          vlan: {
            vlan_id: 1,
            vlan_name: 'default',
            vlan_owner: null,
          },
        },
      ],
      unit: 30,
      user_note: '',
      uuid: '1a3604e7-b66e-4c6a-af45-13aee7c3b4c9',
      warehouse: null,
      warehouse_status: 'in_rack',
      warehouse_status_info: null,
      warranty: null,
    },
  ],
  size: 22,
};

"https://ds.smartape.net/api/dci/v3/server?orderby=configuration%20asc&limit=4,18&where=(owner_email%20EQ%20%27gamebrolive@gmail.com%27)+AND+is_new%20EQ%20false+AND+location_id%20EQ%203"

const outList = (server) => {
  const reuslt = `${server.barcode} ${server.rack.name} юнит ${server.unit}`;

  const switchInfo = (switchArray) => {
    return switchArray.map((el) => `${el.switch_name} ${el.description}`).join('\n');
  };

  const conn = switchInfo(server.switch_connection);
  return `${reuslt}\n${conn}\n`;
};

console.log(srcObj.list.map((el) => outList(el)).join('\n'));
